services:
  marketplace-messanger-api:
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: always
    image: marketplace-messanger-api
    container_name: marketplace-messanger-api
    volumes:
      - /home/kinoko/logs/marketplace-messanger-api:/logs
    #      - ./logs:/logs                             # Для отладки на windows машине
    networks:
      - backend
    ports:
      - "33305:33305"

networks:
  backend:
    external: true
